# Omakase Ruby styling for Rails
inherit_gem: {rubocop-rails-omakase: rubocop.yml}
# Overwrite or add rules to create your own house style

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument
